-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Sales CRM, v1 by george.schulz33@gmail.com **



-- ************************************** external_data

CREATE TABLE external_data
(
 account_id serial NOT NULL,
 first_name varchar(50) NOT NULL,
 last_name  varchar(50) NOT NULL,
 email      varchar(80) NOT NULL,
 phone      varchar(90) NOT NULL,
 address    varchar(100) NOT NULL,
 city       varchar(80) NOT NULL,
 "state"      varchar(20) NOT NULL,
 zip        varchar(10) NOT NULL,
 account    varchar(50) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( account_id )
);








-- ************************************** businesses

CREATE TABLE businesses
(
 business_id   serial NOT NULL,
 name          varchar(90) NOT NULL,
 billing_email varchar(80) NOT NULL,
 CONSTRAINT PK_2 PRIMARY KEY ( business_id )
);








-- ************************************** users

CREATE TABLE users
(
 user_id     serial NOT NULL,
 first_name  varchar(50) NOT NULL,
 business_id int NOT NULL,
 last_anme   varchar(50) NOT NULL,
 email       varchar(80) NOT NULL,
 password    varchar(255) NOT NULL,
 role        varchar(50) NOT NULL,
 CONSTRAINT PK_3 PRIMARY KEY ( user_id ),
 CONSTRAINT FK_9 FOREIGN KEY ( business_id ) REFERENCES businesses ( business_id )
);

CREATE INDEX FK_99 ON users
(
 business_id
);








-- ************************************** pipelines

CREATE TABLE pipelines
(
 pipeline_id serial NOT NULL,
 name        varchar(50) NOT NULL,
 business_id int NOT NULL,
 config      json NOT NULL,
 CONSTRAINT PK_4 PRIMARY KEY ( pipeline_id ),
 CONSTRAINT FK_5 FOREIGN KEY ( business_id ) REFERENCES businesses ( business_id )
);

CREATE INDEX FK_2 ON pipelines
(
 business_id
);








-- ************************************** stages

CREATE TABLE stages
(
 stage_id    serial NOT NULL,
 pipeline_id int NOT NULL,
 name        varchar(50) NOT NULL,
 CONSTRAINT PK_5 PRIMARY KEY ( stage_id ),
 CONSTRAINT FK_7 FOREIGN KEY ( pipeline_id ) REFERENCES pipelines ( pipeline_id )
);

CREATE INDEX FK_11 ON stages
(
 pipeline_id
);








-- ************************************** leads

CREATE TABLE leads
(
 lead_id            serial NOT NULL,
 first_name         varchar(50) NOT NULL,
 user_id            int NOT NULL,
 stage_id           int NOT NULL,
 last_name          varchar(50) NOT NULL,
 address            varchar(150) NOT NULL,
 city               varchar(50) NOT NULL,
 "state"              varchar(2) NOT NULL,
 zip                varchar(10) NOT NULL,
 lead_type          varchar(50) NOT NULL,
 "source"             varchar(50) NOT NULL,
 email              varchar(50) NOT NULL,
 phone              varchar(10) NOT NULL,
 close_status       varchar(15) NOT NULL,
 date_created       timestamp NOT NULL,
 setup_payment      boolean NOT NULL,
 setup_initial      boolean NOT NULL,
 is_commission_paid numeric NOT NULL,
 commission_value   numeric NOT NULL,
 CONSTRAINT PK_6 PRIMARY KEY ( lead_id ),
 CONSTRAINT FK_6 FOREIGN KEY ( stage_id ) REFERENCES stages ( stage_id ),
 CONSTRAINT FK_8 FOREIGN KEY ( user_id ) REFERENCES users ( user_id )
);

CREATE INDEX FK_12 ON leads
(
 stage_id
);

CREATE INDEX FK_3 ON leads
(
 user_id
);








-- ************************************** tasks

CREATE TABLE tasks
(
 task_id  serial NOT NULL,
 name     text NOT NULL,
 lead_id  int NOT NULL,
 details  text NOT NULL,
 due_date date NOT NULL,
 priority varchar(50) NOT NULL,
 is_done  boolean NOT NULL,
 CONSTRAINT PK_7 PRIMARY KEY ( task_id ),
 CONSTRAINT FK_3 FOREIGN KEY ( lead_id ) REFERENCES leads ( lead_id )
);

CREATE INDEX FK_44 ON tasks
(
 lead_id
);








-- ************************************** notes

CREATE TABLE notes
(
 note_id serial NOT NULL,
 lead_id int NOT NULL,
 note    text NOT NULL,
 CONSTRAINT PK_8 PRIMARY KEY ( note_id ),
 CONSTRAINT FK_1 FOREIGN KEY ( lead_id ) REFERENCES leads ( lead_id )
);

CREATE INDEX FK_34 ON notes
(
 lead_id
);








-- ************************************** agreements

CREATE TABLE agreements
(
 agreement_id      serial NOT NULL,
 lead_id           int NOT NULL,
 billing_type      varchar(50) NOT NULL,
 billing_account   numeric NOT NULL,
 setup_fee         numeric NOT NULL,
 instrutions       text NOT NULL,
 send_type         varchar(50) NOT NULL,
 service           varchar(50) NOT NULL,
 long_link         text NOT NULL,
 short_link        text NOT NULL,
 includes_roents   boolean NOT NULL,
 includes_interior boolean NOT NULL,
 includes_roaches  boolean NOT NULL,
 linear_feet       numeric NOT NULL,
 start_month       varchar(50) NOT NULL,
 end_month         varchar(50) NOT NULL,
 sentricon_type    varchar(50) NOT NULL,
 created           timestamp NOT NULL,
 is_signed         boolean NOT NULL,
 CONSTRAINT PK_9 PRIMARY KEY ( agreement_id ),
 CONSTRAINT FK_43 FOREIGN KEY ( lead_id ) REFERENCES leads ( lead_id )
);

CREATE INDEX FK_21 ON agreements
(
 lead_id
);








-- ************************************** actions

CREATE TABLE actions
(
 action_id serial NOT NULL,
 name      varchar(50) NOT NULL,
 lead_id   int NOT NULL,
 complete  boolean NOT NULL,
 detail    text NOT NULL,
 CONSTRAINT PK_10 PRIMARY KEY ( action_id ),
 CONSTRAINT FK_233 FOREIGN KEY ( lead_id ) REFERENCES leads ( lead_id )
);

CREATE INDEX FK_23 ON actions
(
 lead_id
);







